version = "1.0"

[main]
name = "Liaison QSSE"

    [main.gateway]
    name = "Passerelle Dolibarr ARCenal QSSE"

        [main.gateway.gateway_url]
        ask = "URL HTTPS de la passerelle"
        type = "string"

        [main.gateway.gateway_key]
        ask = "Nouvelle clé de liaison"
        type = "string"
