#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/tests.v1.schema.json

test_format = 1.0

[default]
args.gateway_url = "https://dolibarr.example.org/custom/arcenalqsse/gateway.php"
args.gateway_key = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
