<?php
// Generated by ARCenal Bridge. This file is outside the web root.
return [
    'trusted_sso' => true,
    'paired' => false,
    'gateway_url' => '',
    'gateway_key' => '',
    'sirh_paired' => false,
    'sirh_gateway_url' => '',
    'sirh_gateway_key' => '',
    'sirh_gateway_entity' => 0,
];
