env[ARCENAL_PORTAL_CONFIG] = __INSTALL_DIR__/config.php
php_admin_value[upload_max_filesize] = 3M
php_admin_value[post_max_size] = 3M
php_admin_value[session.cookie_httponly] = 1
php_admin_value[session.cookie_secure] = 1
