<?php
// SPDX-License-Identifier: GPL-3.0-or-later
// Deploy only behind SSOwat, which strips client identity headers and authenticates every request.
$configPath=getenv('ARCENAL_PORTAL_CONFIG')?:'/etc/arcenal-qsse-portal/config.php';
if(!is_file($configPath)){http_response_code(503);exit('Portail non configuré.');}
$config=require $configPath;
if(!is_array($config)||empty($config['trusted_sso'])||!filter_var($config['gateway_url']??'',FILTER_VALIDATE_URL)||parse_url($config['gateway_url'],PHP_URL_SCHEME)!=='https') {http_response_code(503);exit('Configuration de sécurité incomplète.');}
$uid=$_SERVER['HTTP_REMOTE_USER']??$_SERVER['HTTP_YNH_USER']??'';
if(!preg_match('/^[a-zA-Z0-9._@-]{1,100}$/D',$uid)){http_response_code(401);exit('Connectez-vous depuis ARCenal Système.');}
session_set_cookie_params(['httponly'=>true,'secure'=>true,'samesite'=>'Strict']);
session_start();
if(($_SESSION['uid']??'')!==$uid){session_regenerate_id(true);$_SESSION=['uid'=>$uid,'csrf'=>bin2hex(random_bytes(32))];}
header("Content-Security-Policy: default-src 'none'; style-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'");header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
function esc($s):string{return htmlspecialchars((string)$s,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
function gateway(array $input):array{
    global $config,$uid;
    $input['uid']=$uid;$body=json_encode($input,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);$ts=(string)time();$nonce=bin2hex(random_bytes(16));
    $sig=hash_hmac('sha256',$ts."\n".$nonce."\n".$body,$config['gateway_key']);
    $ch=curl_init($config['gateway_url']);curl_setopt_array($ch,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$body,CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>15,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_PROTOCOLS=>CURLPROTO_HTTPS,CURLOPT_HTTPHEADER=>['Content-Type: application/json','X-Arcenal-Timestamp: '.$ts,'X-Arcenal-Nonce: '.$nonce,'X-Arcenal-Signature: '.$sig]]);
    $response=curl_exec($ch);$code=curl_getinfo($ch,CURLINFO_HTTP_CODE);curl_close($ch);
    if($response===false||$code!==200)throw new RuntimeException('Transmission non confirmée. Conservez votre saisie et réessayez ; si elle a déjà été reçue, elle ne sera pas dupliquée.');
    $data=json_decode($response,true,16,JSON_THROW_ON_ERROR);if(!is_array($data))throw new RuntimeException('Réponse indisponible.');return $data;
}
$error='';$success='';$sent=false;$data=['identity'=>$uid,'records'=>[],'actions'=>[]];
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!is_string($_POST['csrf']??null)||!hash_equals($_SESSION['csrf'],$_POST['csrf'])){http_response_code(403);exit('Formulaire expiré.');}
    try{
        if(($_POST['form']??'report')==='action'){
            $res=gateway(['operation'=>'action.progress','request_id'=>(string)($_POST['request_id']??''),'action_id'=>(int)($_POST['action_id']??0),'version'=>(int)($_POST['version']??0),'progress'=>(int)($_POST['progress']??-1),'note'=>(string)($_POST['note']??'')]);$success='Avancement enregistré pour '.$res['reference'].'.';
        }elseif(($_POST['form']??'report')==='mat'){
            $input=[];foreach(['mat_feeling','mat_equipment','mat_documents','mat_conditions','mat_risks','observation'] as $field)$input[$field]=is_string($_POST[$field]??null)?$_POST[$field]:'';$res=gateway(['operation'=>'mat.submit','request_id'=>(string)($_SESSION['mat_request_id']??''),'record'=>$input]);$success=$res['alert']?'MAT enregistrée. Prends immédiatement contact avec ton responsable et ne débute pas le travail dans ces conditions.':'MAT enregistrée. Bonne journée, bon travail et prends soin de toi.';unset($_SESSION['mat_request_id']);
        }else{
            $input=[];foreach(['title','description','context_label','location','occurred_at','origin','immediate_action','category','severity','report_type','nc_type','analysis_immediate'] as $field)$input[$field]=is_string($_POST[$field]??null)?$_POST[$field]:'';
            if(!empty($_FILES['photo']['tmp_name'])){if((int)$_FILES['photo']['error']!==UPLOAD_ERR_OK||(int)$_FILES['photo']['size']>2097152)throw new RuntimeException('Photo invalide ou supérieure à 2 Mo.');$input['photo']=['name'=>(string)$_FILES['photo']['name'],'content'=>base64_encode((string)file_get_contents($_FILES['photo']['tmp_name']))];}
            $res=gateway(['operation'=>'submit','request_id'=>(string)($_SESSION['request_id']??''),'record'=>$input]);$success='Remontée reçue : '.$res['reference'];$sent=true;unset($_SESSION['request_id']);
        }
    }catch(Throwable $e){$error=$e->getMessage();}
}
try{$data=gateway(['operation'=>'list']);}catch(Throwable $e){$error=$error?:'Vos remontées sont temporairement indisponibles ou votre accès a été retiré.';}
$_SESSION['request_id']=$_SESSION['request_id']??bin2hex(random_bytes(16));$_SESSION['mat_request_id']=$_SESSION['mat_request_id']??bin2hex(random_bytes(16));
$states=['submitted'=>'Soumise','qualified'=>'Qualifiée','treatment'=>'En traitement','closed'=>'Close','classified'=>'Classée avec motif'];
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mon espace QSSE — ARCenal</title><link rel="stylesheet" href="qsse.css"></head><body><main class="aq"><header class="aq-hero"><div><span class="aq-eyebrow">ARCENAL / MON ESPACE</span><h1>Agir pour un terrain plus sûr</h1><p><?=esc($data['identity'])?> · Portail équipier</p></div><span class="aq-beta">BÊTA 0.4.2</span></header>
<?php if($error):?><p class="aq-error" role="alert"><?=esc($error)?></p><?php endif;?><?php if($success):?><p class="aq-success" role="status"><?=esc($success)?></p><?php endif;?>
<section class="aq-panel"><h2>Mes services ARCenal</h2><div class="aq-grid"><p><strong>QSSE</strong><br>MAT, remontées terrain et actions PAO.</p><p><strong>SIRH</strong><br>Emplacement réservé au module indépendant de Damien.</p></div></section>
<form method="post" class="aq-panel aq-form"><h2>Ma mise au travail (MAT)</h2><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><input type="hidden" name="form" value="mat"><label>Comment te sens-tu ?<select name="mat_feeling" required><option value="sun">☀️ Bien</option><option value="cloud">☁️ Moyen</option><option value="storm">⛈️ Mal</option></select></label><?php foreach(['mat_equipment'=>'J’ai mon matériel et mes EPI','mat_documents'=>'Je maîtrise le PDP, le mode opératoire et la coactivité','mat_conditions'=>'Les conditions d’exécution sont réunies'] as $field=>$label):?><label><?=esc($label)?><select name="<?=esc($field)?>" required><option value="yes">Oui</option><option value="no">Non</option></select></label><?php endforeach;?><label>Les principaux risques sont maîtrisés<select name="mat_risks" required><option value="yes">Oui</option><option value="alert">Non, j’alerte</option></select></label><label>Observation<textarea name="observation" maxlength="5000" rows="3"></textarea></label><button class="aq-button">Enregistrer ma MAT</button></form>
<form method="post" enctype="multipart/form-data" class="aq-panel aq-form"><h2>Faire une remontée</h2><p>En cas de danger immédiat, appliquez les consignes d’urgence du site et prévenez votre responsable. Ce formulaire ne remplace pas l’alerte terrain.</p><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>">
<?php foreach(['title'=>'Titre','context_label'=>'Site / activité'] as $field=>$label):?><label><?=esc($label)?><input name="<?=esc($field)?>" maxlength="180" <?=$field==='title'?'required':''?> value="<?=esc(!$sent?($_POST[$field]??''):'')?>"></label><?php endforeach;?>
<label>Faits observés<textarea name="description" maxlength="10000" rows="5" required><?=esc(!$sent?($_POST['description']??''):'')?></textarea></label><div class="aq-grid"><label>Lieu précis<input name="location" maxlength="180"></label><label>Date et heure<input type="datetime-local" name="occurred_at"></label></div><label>Type de remontée<select name="report_type" required><option value="dangerous_situation">Situation dangereuse</option><option value="nonconformity">Non-conformité</option><option value="good_point">Bon point sécurité / qualité</option><option value="improvement_idea">Idée d’amélioration</option></select></label><label>Type de non-conformité<select name="nc_type"><option value="">Sans objet</option><option value="documentary">Documentaire</option><option value="operational">Opérationnelle</option><option value="regulatory">Réglementaire</option><option value="material">Matérielle</option><option value="organizational">Organisationnelle</option></select></label><label>Analyse immédiate<textarea name="analysis_immediate" maxlength="5000" rows="3"></textarea></label><label>Action immédiate<textarea name="immediate_action" maxlength="5000" rows="3"></textarea></label><div class="aq-grid"><label>Catégorie<select name="category"><?php foreach(['danger'=>'Déplacement, chute, glissade','ppe'=>'EPI','environment'=>'Environnement','equipment'=>'Outillage, machine, équipement','hazardous_product'=>'Produit dangereux / rayonnement','fire'=>'Incendie / explosion','electricity'=>'Électricité','ergonomics'=>'Ergonomie','workload'=>'Stress et surcharge de travail','other'=>'Autres'] as $k=>$v):?><option value="<?=esc($k)?>"><?=esc($v)?></option><?php endforeach;?></select></label><label>Criticité<select name="severity"><?php foreach([1=>'🟢',2=>'🟠',3=>'🔴'] as $k=>$v):?><option value="<?=$k?>"><?=esc($v)?></option><?php endforeach;?></select></label></div><label>Photo du constat (JPEG, PNG ou WebP, 2 Mo maximum)<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"></label><input type="hidden" name="origin" value="terrain"><button class="aq-button">Transmettre ma remontée</button><p class="aq-note">La Direction reçoit une notification. Ne renseignez pas de diagnostic médical.</p></form><h2>Mes remontées</h2>
<?php if(!$data['records']):?><p class="aq-panel">Aucune remontée disponible.</p><?php endif;?><?php foreach($data['records'] as $record):?><article class="aq-panel"><small><?=esc($record['ref'])?></small><h3><?=esc($record['title'])?></h3><span class="aq-badge"><?=esc($states[$record['status']]??$record['status'])?></span><p class="aq-pre"><?=esc($record['description'])?></p></article><?php endforeach;?>
<h2>Mes dernières MAT</h2><?php if(empty($data['mats'])):?><p class="aq-panel">Aucune MAT enregistrée.</p><?php endif;?><?php foreach(array_slice($data['mats']??[],0,10) as $mat):?><article class="aq-panel"><small><?=esc($mat['ref'])?> · <?=esc($mat['datec'])?></small><h3><?=esc($mat['title'])?></h3><span class="aq-badge"><?=((int)$mat['severity']===3?'Alerte transmise':'Enregistrée')?></span></article><?php endforeach;?>
<h2>Mes actions PAO</h2><?php if(empty($data['actions'])):?><p class="aq-panel">Aucune action ne vous est affectée ou votre identité n’est pas encore reliée à un utilisateur Dolibarr.</p><?php endif;?><?php foreach(($data['actions']??[]) as $pa):?><article class="aq-panel"><small><?=esc($pa['ref'])?></small><h3><?=esc($pa['title'])?></h3><span class="aq-badge"><?=esc($states[$pa['status']]??$pa['status'])?></span><p>Échéance : <?=esc($pa['due_date']??'—')?> · Avancement : <?=esc($pa['progress']??0)?> %</p><?php if(in_array($pa['status'],['open','in_progress'],true)):?><form method="post" class="aq-form"><input type="hidden" name="csrf" value="<?=esc($_SESSION['csrf'])?>"><input type="hidden" name="form" value="action"><input type="hidden" name="action_id" value="<?=(int)$pa['rowid']?>"><input type="hidden" name="version" value="<?=(int)$pa['version']?>"><input type="hidden" name="request_id" value="<?=esc(bin2hex(random_bytes(16)))?>"><label>Nouvel avancement<input type="number" name="progress" min="0" max="100" value="<?=(int)$pa['progress']?>" required></label><label>Compte rendu<textarea name="note" maxlength="5000" required></textarea></label><button class="aq-button">Actualiser mon action</button></form><?php endif;?></article><?php endforeach;?>
<footer class="aq-foot">ARCenal QSSE · Vous consultez uniquement vos remontées · La fermeture de cet onglet ne déconnecte pas ARCenal Système.</footer></main></body></html>
