#!/bin/bash
# Backup and restore run from YunoHost's temporary work directory.
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers
ynh_backup "$install_dir"
ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"
ynh_backup "/etc/php/$php_version/fpm/pool.d/$app.conf"
